
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  type-aliases-package: com.wanghang.projectsdk.base.entity
  configuration:
    map-underscore-to-camel-case: true